project_id = "wtqkyijzmbvzvpdtflhd"

[functions.generate-course]
verify_jwt = false

[functions.invite-employee]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.send-demo-request]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.scheduled-notifications]
verify_jwt = false

[functions.grade-quiz]
verify_jwt = false

[functions.seed-demo-content]
verify_jwt = false
